from functions_common import get_conn

def generate_student_id(class_code: str):
    conn = get_conn()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT MAX(CAST(student_id AS INTEGER))
        FROM students_id_autogenerated_2
        WHERE class_code = ?
    """, (class_code,))

    max_code = cursor.fetchone()[0]
    conn.close()

    if max_code is None:
        return "001"
    return f"{max_code + 1:03d}"
    
def add_student(department_code: str, class_code: str, name: str, age: int, hometown: str):
    student_id = generate_student_id(class_code)
    
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO students_id_autogenerated_2 (department_code, class_code, student_id, name, age, hometown) 
        VALUES (?, ?, ?, ?, ?, ?)""",
        (department_code, class_code, student_id, name, age, hometown)
    )
    conn.commit()
    conn.close()
    
def get_active_students():
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT * FROM students_id_autogenerated_2 
        WHERE deleted_at IS NULL
        ORDER BY CAST(class_code AS INTEGER), 
        CAST(student_id AS INTEGER)
    """)
    rows = [dict(row) for row in cursor.fetchall()]
    conn.close()
    return rows

def alter_db(new_column: str, type_column: str):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("PRAGMA table_info(students_id_autogenerated_2)")

    rows = cursor.fetchall() 
    columns = [row[1] for row in rows]

    if new_column not in columns:
        # Safe because column names are controlled internally
        cursor.execute(f"ALTER TABLE students_id_autogenerated_2 ADD COLUMN {new_column} {type_column} DEFAULT NULL")

    conn.commit()
    conn.close()

def delete_student(id: str):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM students_id_autogenerated_2 WHERE id=?", (id,))
    conn.commit()
    conn.close()

def expel_student(id: str):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE students_id_autogenerated_2
        SET deleted_at = datetime('now')
        WHERE id = ?
    """, (id,))
    conn.commit()
    conn.close()

def get_expelled_student(start: int, end: int):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT *
        FROM students_id_autogenerated_2
        WHERE deleted_at IS NOT NULL
        LIMIT ? OFFSET ?
    """, (end, start))
    rows = [dict(row) for row in cursor.fetchall()]
    conn.close()
    return rows

def restore_student(id: str):
    conn = get_conn()

    try:
        cursor = conn.cursor()
        cursor.execute("""
            UPDATE students_id_autogenerated_2
            SET deleted_at = NULL
            WHERE id = ?
        """, (id,))
        conn.commit()
        conn.close()

    except Exception as e:
        print("Error:", e)

    finally:
        conn.close()

def get_total_expelled_students():
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT count(id) as total 
        FROM students_id_autogenerated_2 
        WHERE deleted_at IS NOT NULL
    """)
    row = cursor.fetchone()
    conn.close()
    return row["total"]
    
def get_total_attending_students():
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT count(id) as total 
        FROM students_id_autogenerated_2 
        WHERE deleted_at IS NULL
    """)
    row = cursor.fetchone()
    conn.close()
    return row["total"]
