import sqlite3

def get_conn():
    conn = sqlite3.connect(
        "stream_pages/pages_exo/students_id_autogenerated_2.db",
        check_same_thread=False
    )
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn

def init_db():
    conn = get_conn()
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS departments (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            code TEXT UNIQUE NOT NULL,
            name TEXT NOT NULL
        )
    """)
    conn.commit()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS classes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            department_code INTEGER NOT NULL,
            code TEXT NOT NULL,
            name TEXT,
            UNIQUE(department_code, code)
        )
    """)
    conn.commit()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS students_id_autogenerated_2 (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            department_code TEXT NOT NULL,
            class_code TEXT NOT NULL,
            student_id TEXT NOT NULL,
            name TEXT NOT NULL,
            age INTEGER NOT NULL,
            hometown TEXT NOT NULL,
            deleted_at DATETIME DEFAULT NULL,
            UNIQUE(class_code, student_id)
        )          
    """)
    conn.commit()
    conn.close()