import streamlit as st
from functions_exo_5 import *

# -----
# Codes
# -----
st.set_page_config(page_title="Students list with autogenerated id", layout="centered")
st.header("Form to add student's information")

init_db()
alter_db("deleted_at", "DATETIME")

with st.form("add_student", clear_on_submit=True):
    department_code = st.selectbox("Department Code", ["001", "002", "003"])
    class_code = st.selectbox("Class Code", [f"{i:03d}" for i in range(1, 11)])
    name = st.text_input("Student's name")
    age = st.number_input("Student's age", min_value=1, step=1)
    hometown = st.text_input("Student's hometown")

    submit = st.form_submit_button("Add student")

    if submit:
        if not (department_code and class_code and name and hometown):
            st.warning("Please refill all information!")
        else:
            add_student(department_code, class_code, name, age, hometown)
            st.success("Student added!")
            st.rerun()

st.divider()
st.subheader("Students list")

students = get_active_students()

if not students: 
    st.info("There is no student in the list at the moment.")
else:
    for student in students:
        with st.expander(f"{student['id']} - {student['department_code']} {student['class_code']} {student['student_id']} - {student['name']}"):
            st.write(f"Department Code: {student['department_code']}")
            st.write(f"Class Code: {student['class_code']}")
            st.write(f"Age: {student['age']}")
            st.write(f"Hometown: {student['hometown']}")

            if st.button("Delete", key=f"delete_{student['id']}"):
                delete_student(student['id'])
                st.rerun()

            if st.button("Expel", key=f"expel_{student['id']}"):
                expel_student(student['id'])
                st.success("The student has been expelled!")
                st.rerun()