import sqlite3

# ---------------
# Build functions 
# ---------------
def get_conn():
    conn = sqlite3.connect(
        "stream/exo_5/students_id_autogenerated.db",
        check_same_thread=False
    )
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS students_id_autogenerated (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            department_code TEXT NOT NULL,
            class_code TEXT NOT NULL,
            student_id TEXT NOT NULL,
            name TEXT NOT NULL,
            age INTEGER NOT NULL,
            hometown TEXT NOT NULL, 
            UNIQUE(department_code, class_code, student_id)
        )          
    """)
    conn.commit()
    conn.close()

def generate_student_id(department_code: str, class_code: str):
    conn = get_conn()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT MAX(CAST(student_id AS INTEGER))
        FROM students_id_autogenerated
        WHERE department_code = ? AND class_code = ?
    """, (department_code, class_code))

    max_code = cursor.fetchone()[0] # (7,) ==> 7
    conn.close()

    if max_code is None:
        return "001"
    else:
        return f"{max_code + 1:03d}"
    
def add_student(department_code: str, class_code: str, name: str, age: int, hometown: str):
    student_id = generate_student_id(department_code, class_code)
    
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO students_id_autogenerated (department_code, class_code, student_id, name, age, hometown) 
        VALUES (?, ?, ?, ?, ?, ?)""",
        (department_code, class_code, student_id, name, age, hometown)
    )
    conn.commit()
    conn.close()
    
def get_active_students():
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT * FROM students_id_autogenerated 
        WHERE deleted_at IS NULL
        ORDER BY CAST(department_code AS INTEGER), 
        CAST(class_code AS INTEGER), 
        CAST(student_id AS INTEGER)
    """)
    rows = cursor.fetchall()
    conn.close()
    return rows

def alter_db(new_column: str, type_column: str):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("PRAGMA table_info(students_id_autogenerated)")

    rows = cursor.fetchall() # Store in rows to keep the datas
    columns = [row[1] for row in rows]

    if new_column not in columns:
        cursor.execute(f"ALTER TABLE students_id_autogenerated ADD COLUMN {new_column} {type_column} DEFAULT NULL")

    conn.commit()
    conn.close()

def delete_student(id: str):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM students_id_autogenerated WHERE id=?", (id,))
    conn.commit()
    conn.close()

def expel_student(id: str):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE students_id_autogenerated
        SET deleted_at = datetime('now')
        WHERE id = ?
    """, (id,))
    conn.commit()
    conn.close()

def get_expelled_student():
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT *
        FROM students_id_autogenerated
        WHERE deleted_at IS NOT NULL
    """)
    rows = cursor.fetchall()
    conn.close()
    return rows

def restore_student(student_id: str):
    conn = get_conn()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE students_id_autogenerated
        SET deleted_at = NULL
        WHERE student_id = ?
    """, (student_id,))
    conn.commit()
    conn.close()
